;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        helm-M-x
        org-beginning-of-line
        org-ctrl-c-ctrl-c
        org-end-of-line
        org-return
        org-self-insert-command
        org-shiftmetaleft
        org-shiftup
        simpleclip-paste
        ))

(setq mc/cmds-to-run-once
      '(
        ))
